version: "3"
services:

  database:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=mama
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 3G
      restart_policy:
        condition: on-failure

    ports:
            - "3306:3306"
    networks:
      - webnet


  client:
    image: shawney/client:latest
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure

    networks:
      - webnet


  admin:
    image: shawney/mysql-admin:latest
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure

    networks:
      - webnet
  
  server:
    image: shawney/gs-rest-service:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 3G
      restart_policy:
        condition: on-failure
    depends_on:
      - "database"
    ports:
            - "8080:8080"
    networks:
      - webnet
    
  
networks:
  webnet:
