version: "3"
services:

  textclient:
    image: textclient:latest
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    networks:
      - webnet

  mysqldatabase:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    ports:
            - "3306:3306"
    networks:
      - webnet

  admininterface:
    image: admininterface:latest
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    networks:
      - webnet
  
  restserver:
    image: restserver:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
            - "8080:8080"
    networks:
      - webnet
    
  
networks:
  webnet:
