/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAD_H_RPCGEN
#define _LOAD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct var {
	char resp[4];
	long p;
	long q;
};
typedef struct var var;

#define LOAD_PROG 123456789
#define LOAD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_PRIME 3
extern  var * get_prime_1(long *, CLIENT *);
extern  var * get_prime_1_svc(long *, struct svc_req *);
extern int load_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_PRIME 3
extern  var * get_prime_1();
extern  var * get_prime_1_svc();
extern int load_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_var (XDR *, var*);

#else /* K&R C */
extern bool_t xdr_var ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOAD_H_RPCGEN */
